#!/bin/bash

composer install

doctrine="$PWD/vendor/bin/doctrine"

if [[ -n "$DB" ]]; then
    echo "Configuring unit tests for a $DB database"

    cp .travis/${DB}_bootstrap_doctrine.php tests/doctrine/bootstrap_doctrine.php
    cp .travis/${DB}_bootstrap_pdo.php tests/doctrine/bootstrap_pdo.php
    cd tests/doctrine
    $doctrine orm:schema-tool:create
else
    echo 'Cannot setup unit tests, $DB is not defined.'
    exit 1
fi
